#!/usr/bin/zsh
OFFSET_CURSOR="$(($#BUFFER-CURSOR))"
if [ -z "$BUFFER" ]; then
  BUFFER="$history[$((HISTCMD-1))]"
fi
BUFFER="$(echo "sudo $BUFFER" | sed "s/sudo sudo //")"
CURSOR="$(($#BUFFER-OFFSET_CURSOR))"
