#!/usr/bin/zsh
local PKG_MAN=$(pkg_man)

link "${HOME}/src/nvim" "${HOME}/.config/nvim"
cat "${HOME}/.config/crontab" | crontab 1> /dev/null

# LOAD EXTERNALS
program zsh
program fzf
program nvim neovim
setup git "${GIT_BIN}" "${PKG_MAN} git"
program python3
program luarocks
program hyperfine
program mosh
if is-laptop; then
  program kitty
  program rustup
fi
crate bat
setup zsh-patina "$_ZSH_PATINA_PATH" "cargo install zsh-patina"
dotfile zshrc
dotfile zshenv
dotfile gitconfig
