#!/usr/bin/zsh
if [[ ! -n $ZDOTDIR ]]; then
  echo "export ZDOTDIR=\"\${ZDOTDIR:-\$XDG_CONFIG_HOME/.config/zsh/}\"" >> $PREFIX/etc/zshrc
  echo "Setting ZDOTDIR" 2> /dev/stderr
  source $PREFIX/etc/zshrc
fi

local PKG_MAN=$(pkg_man)

link "${HOME}/src/nvim" "${HOME}/.config/nvim"
link "${HOME}/.config/cargo/config.toml" "${XDG_DATA_HOME}/cargo/config.toml"
cat "${HOME}/.config/crontab" | crontab 1> /dev/null

# LOAD EXTERNALS
program zsh
program fzf
program nvim neovim
setup git "${GIT_BIN}" "${PKG_MAN} git"
program python3
program luarocks
program hyperfine
program mosh
if is-laptop; then
  program kitty
  program rustup
fi
program sccache
crate bat
setup zsh-patina "$_ZSH_PATINA_PATH" "cargo install zsh-patina"
dotfile termux
