# ALIASES

alias battery_level='python -c "print(str(round(100*$(cat /sys/class/power_supply/BAT0/energy_now) / $(cat /sys/class/power_supply/BAT0/energy_full))))"'
alias matches="grep -o"
alias -g withFire="-9"
alias zrctime="hyperfine --warmup 3 --min-runs 10 'zsh -i -c exit' -i"
alias zrcprof="time ZSH_DEBUGRC=1 zsh -i -c exit"

alias .="clear;s"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias pv="pv -c"

alias la="ls -a"
alias ll="ls -la"

alias cl="less -r -f +G +g .c.log"
alias tl="less -r -f +G +g .t.log"

alias sync='((a . && m "Backup $(date)") || true) && pP'
alias "sn"="sync_notes"
alias "a."="a ."
alias cp="cp -r"
alias ci="r"
alias g++="g++ -std=c++14 -Wall -Werror"
alias ghc="ghc -Wall"
alias ghct="ghc -Wall -O2 -threaded -rtsopts -with-rtsopts='-N4'"
alias got="git"
alias grep="grep -E"
alias ma0="map"
alias mapo="map"
alias amp="map"
alias mao="map"
alias npmm="npm"
alias turbo="npm exec turbo --"
alias tsc="npm exec tsc --"
alias vite="npm exec vite --"
alias vitest="npm exec vitest --"
alias func="npm exec func --"
alias nt="cargo nextest run"
alias q="exit"
alias reauthor="git commit --amend --no-edit --author='Eleanor Pratt <ellie@skfl.tech>'"
alias td="RUST_LOG=\"debug\" cargo test"
alias ti="RUST_LOG=\"info\" cargo test"
alias tt="RUST_LOG=\"trace\" cargo test"

alias open="xdg-open"
alias v="\$EDITOR "
alias vi="\$EDITOR "
alias vim="\$EDITOR "
alias zed="\$EDITOR "
alias :e="\$EDITOR "
alias zrc="pushd ${HOME}/.config; \$EDITOR ${HOME}/.config/zshrc ${HOME}/.config/*.zsh ${HOME}/.config/zsh_plugins.txt; popd"
alias grc="\$EDITOR ${HOME}/.config/gitconfig"
alias vrc="\$EDITOR ${HOME}/.config/nvim/lua/compilersEllie/**/*.lua"
alias icat="kitty +kitten icat"
alias bob="${HOME}/skfltech/skfl/bob.ts"
