#!/usr/bin/zsh
local filename="$1"
local extension="${2:=${filename##*.}}"
if [[ ! -f "$filename" ]]; then
  echo "Error: File '$filename' does not exist."
  return 1
fi
tail -f "$filename" | bat -l "$extension" --paging=never
