# EXPORTS
export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
export GIT_BIN="$(which git)"
export ANTIDOTE_HOME="$HOME/.cache/antidote"
export CARGO_HOME="$HOME/.cache/cargo"
export CARGO_TARGET_DIR="$CARGO_HOME/target"
export CARGO_INCREMENTAL=0
export ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"

export WORDCHARS=' *?_-.[]~=\\/&;!#$%^(){}<>'
export KEYTIMEOUT=0.1
export TERM="xterm-256color"
export MAGIC_ENTER_GIT_COMMAND='s'
export MAGIC_ENTER_OTHER_COMMAND='s'
export TAB="\t"

# TOOL SETTINGS
export LLVM_SYS_221_PREFIX="/mnt/big/llvm-project/build"
if [ ! -n "$EDITOR" ]; then
  if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    export EDITOR="$(echo -e "$(which nvim || which vim)" | tail -n 1)"
  else
    export EDITOR="$(echo -e "$(which zed || which nvim || which vim)" | tail -n 1)"
  fi
fi
export VISUAL="\$EDITOR"

export NVM_LAZY_LOAD=true
export NVM_COMPLETION=true

export OLLAMA_REQUEST_TIMEOUT=600
export OLLAMA_FLASH_ATTENTION=1
export OLLAMA_KV_CACHE_TYPE=q8_0

# HISTORY
export HISTSIZE=1000000 # set history size
export SAVEHIST=1000000 # save history after logout
export HISTFILE=$HOME/.local/share/zsh_history  # history file
export HISTIGNORE="^(fg|bg|ls|s|p|q|cd|exit)$"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=yellow"

# Set up path!
path=(
  "/data/data/com.termux/files/usr/bin/"
  "/usr/bin:/usr/sbin"
  "/var/lib/snapd/snap/bin"
  "/usr/local/bin"
  "/opt/local/bin"
  "/usr/local/sbin"
  "/usr/local/cuda-12.5/bin"
  "$HOME/.dotnet/tools"
  "$HOME/.rbenv/bin"
  "$HOME/.npm-global/bin"
  "$HOME/.local/share/pi-node/node-v22.23.2-linux-x64/bin"
  "$HOME/.cache/cargo/bin"
  "$HOME/.local/share/fzf/bin"
  "$HOME/.local/bin"
  "$HOME/.config/bin"
)
export PATH="$PATH"
